Repository Driftmeta/flutter_catalog, pull requests merged in 2023-11, with the labels that each got.

#55 54: updated alignment ui
  lib/property_fields/alignment_field.dart
  lib/widgets/fields/alignment_field.dart
Labels: property field

#65 35: create boolean ui
  lib/widgets/fields/boolean_field.dart
Labels: property field

#69 #68: created icon options view
  lib/widgets/fields/axis_field.dart
  lib/widgets/icon_options.dart
  lib/widgets/radio_button.dart
  pubspec.lock
Labels: enhancement

#73 72: PropertyWidget class
  lib/widgets/core/property.dart
  pubspec.lock
Labels: architecture

#77 75: Property Previewer
  lib/widgets/core/property_previewer.dart
Labels: architecture

#82 81: Fixed types issue in IconOptions
  lib/widgets/fields/axis_field.dart
  lib/widgets/fields/curve_field.dart
  lib/widgets/icon_options.dart
Labels: architecture
